"""create_process_domain_tables

Revision ID: 3ae4702f5dcb
Revises: 16fa5c3029b0
Create Date: 2026-04-20 02:25:14.066860

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ae4702f5dcb"
down_revision: Union[str, Sequence[str], None] = "16fa5c3029b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sectors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("acronym", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sectors_acronym"), "sectors", ["acronym"], unique=True)
    op.create_table(
        "processes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "short_description",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=False,
        ),
        sa.Column("full_description", sa.Text(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "RH",
                "MATERIAIS",
                "FINANCEIRO",
                "TECNOLOGIA",
                "INFRAESTRUTURA",
                "CONTRATACOES",
                name="processcategory",
            ),
            nullable=False,
        ),
        sa.Column(
            "estimated_time",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=False,
        ),
        sa.Column("requirements", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("access_count", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "IN_REVIEW", "PUBLISHED", "ARCHIVED", name="processstatus"
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["approved_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_processes_approved_by"), "processes", ["approved_by"], unique=False
    )
    op.create_index(
        op.f("ix_processes_category"), "processes", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_processes_created_by"), "processes", ["created_by"], unique=False
    )
    op.create_index(op.f("ix_processes_status"), "processes", ["status"], unique=False)
    op.create_index(op.f("ix_processes_title"), "processes", ["title"], unique=False)
    op.create_table(
        "flow_steps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("process_id", sa.Uuid(), nullable=False),
        sa.Column("sector_id", sa.Uuid(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "responsible", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "estimated_time",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["process_id"], ["processes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sector_id"], ["sectors.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_flow_steps_process_id"), "flow_steps", ["process_id"], unique=False
    )
    op.create_index(
        op.f("ix_flow_steps_sector_id"), "flow_steps", ["sector_id"], unique=False
    )
    op.create_table(
        "step_resources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("step_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("DOCUMENT", "LEGAL_BASIS", "POP", "LINK", name="resourcetype"),
            nullable=False,
        ),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["step_id"], ["flow_steps.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_step_resources_step_id"), "step_resources", ["step_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_step_resources_step_id"), table_name="step_resources")
    op.drop_table("step_resources")
    op.drop_index(op.f("ix_flow_steps_sector_id"), table_name="flow_steps")
    op.drop_index(op.f("ix_flow_steps_process_id"), table_name="flow_steps")
    op.drop_table("flow_steps")
    op.drop_index(op.f("ix_processes_title"), table_name="processes")
    op.drop_index(op.f("ix_processes_status"), table_name="processes")
    op.drop_index(op.f("ix_processes_created_by"), table_name="processes")
    op.drop_index(op.f("ix_processes_category"), table_name="processes")
    op.drop_index(op.f("ix_processes_approved_by"), table_name="processes")
    op.drop_table("processes")
    op.drop_index(op.f("ix_sectors_acronym"), table_name="sectors")
    op.drop_table("sectors")
    # Tipos Enum nomeados sao criados automaticamente pelo Postgres quando a
    # coluna e declarada, mas nao sao dropados junto com a tabela — precisamos
    # limpar manualmente para que o downgrade seja idempotente.
    sa.Enum(name="resourcetype").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="processstatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="processcategory").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
